// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsJEkeP4QQ56iMvaWO41WiLs18BD9Y6M',
    appId: '1:757955392650:web:a0bcd04167da4dbea0a973',
    messagingSenderId: '757955392650',
    projectId: 'recipe-project-f257b',
    authDomain: 'recipe-project-f257b.firebaseapp.com',
    storageBucket: 'recipe-project-f257b.appspot.com',
    measurementId: 'G-EFVJ29XF5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNRk5WC5sJ6r8soB-La1GMmZddJ9UBF0',
    appId: '1:757955392650:android:0658c0c433ee4c45a0a973',
    messagingSenderId: '757955392650',
    projectId: 'recipe-project-f257b',
    storageBucket: 'recipe-project-f257b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5T9M0l0YxecrVJ2lE6N772HO7gkEk0g',
    appId: '1:757955392650:ios:80c5cda96948410fa0a973',
    messagingSenderId: '757955392650',
    projectId: 'recipe-project-f257b',
    storageBucket: 'recipe-project-f257b.appspot.com',
    iosClientId: '757955392650-oghbsk3rq977hvoi9s6fkgjqvk56i4o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab01Recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5T9M0l0YxecrVJ2lE6N772HO7gkEk0g',
    appId: '1:757955392650:ios:80c5cda96948410fa0a973',
    messagingSenderId: '757955392650',
    projectId: 'recipe-project-f257b',
    storageBucket: 'recipe-project-f257b.appspot.com',
    iosClientId: '757955392650-oghbsk3rq977hvoi9s6fkgjqvk56i4o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab01Recipe',
  );
}
